name: asdf-plugin-test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: asdf-vm/actions/plugin-test@v2
        with:
          command: calicoctl --help
